language: c
compiler: gcc


addons:
  coverity_scan:
    project:
      name: "jonpe960/ufsm"
      description: "Build submitted via Travis CI"
    notification_email: jonpe960@gmail.com
    build_command_prepend: ""
    build_command:   "make"
    branch_pattern: "*"

script: make
